Resources:
  AWSClassifySessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: classifySessionStore.${self:custom.domainName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true
      GlobalSecondaryIndexes:
      - IndexName: userId
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
      StreamSpecification:
        StreamViewType: ${self:custom.SessionStreamViewType, 'NEW_AND_OLD_IMAGES'}